name: Build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 5' # Every Friday at 06:00 UTC
  push:
    branches:
      - '**'
    paths-ignore:
      - '*.md'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    name: Test Build
    strategy:
      matrix:
        addon: 
          - zabbix60-agent2
          - zabbix70-agent2
        target:
          - arch: amd64
            os: ubuntu-24.04
          - arch: aarch64
            os: ubuntu-24.04-arm
    runs-on: ${{ matrix.target.os }}
    permissions:
      contents: read
      id-token: read
      packages: read
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    
    - name: Container Test Build
      uses: home-assistant/builder/actions/build-image@2026.03.2
      with:
        arch: ${{ matrix.target.arch }}
        image: ghcr.io/chrschu/ha-${{ matrix.addon }}-${{ matrix.target.arch }}
        context: ./${{ matrix.addon }}
        image-tags: ci
        push: false
        version: 0.0.1 # Dummy version to prevent buildx from skipping the build
        container-registry: ghcr.io
        container-registry-username: ${{ github.repository_owner }}
        container-registry-password: ${{ secrets.GITHUB_TOKEN }}
        cache-gha: false
        cosign: false
